export PATH=${HOME}/bin:/usr/local/bin:${PATH}
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="robbyrussell"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy/mm/dd"
export NVM_LAZY_LOAD=true

plugins=(git colored-man-pages colorize git-prompt sudo zsh-nvm)

source ${ZSH}/oh-my-zsh.sh

fpath+=${HOME}/.zsh-functions

for script in ${HOME}/.zshrc.d/*.sh; do
  source ${script}
done
